# Ef-Bio - kitty color config
# Theme  by Protesilaos Stavrou (https://protesilaos.com/codelog/2022-10-02-ef-themes-bio-theme/)

background #111111
foreground #cfdfd5
selection_background #cfdfd5
selection_foreground #111111
url_color #b1b1b1
cursor #cfdfd5
active_border_color #808f80
inactive_border_color #212121
active_tab_background #111111
active_tab_foreground #cfdfd5
inactive_tab_background #212121
inactive_tab_foreground #404240
tab_bar_background #212121

# normal
color0 #404240
color1 #ef6560
color2 #3fb83f
color3 #d4aa02
color4 #37aff6
color5 #d38faf
color6 #6fc5ef
color7 #cfdfd5

# bright
color8 #808f80
color9 #ff778f
color10 #00c089
color11 #cfc04f
color12 #32cfef
color13 #af9fff
color14 #5dc0aa
color15 #8fcfaf