font_family	 Source Code Pro Medium
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13.0

# tab separator style
tab_bar_style separator

# custom keybindings map ctrl++enter new_window
map ctrl+q close_tab
map ctrl+tab next_tab

# splits 
map F5 launch --location=hsplit
map F6 launch --location=vsplit
map F7 layout_action rotate
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# force swayland; window decorations currently don't work on wayland itself 
linux_display_server x11

# vim:ft=kitty


## name: Solarized Light
## author: Ethan Schoonover
## license: MIT
## blurb: Precision colors for machines and people

# The basic colors
foreground              #657b83
background              #fdf6e3
selection_foreground    #586e75
selection_background    #eee8d5

# Cursor colors
cursor                  #657b83
cursor_text_color       #fdf6e3

# kitty window border colors
active_border_color     #cb4b16
inactive_border_color   #93a1a1

# Tab bar colors
active_tab_background   #fdf6e3
active_tab_foreground   #657b83
inactive_tab_background #93a1a1
inactive_tab_foreground #fdf6e3

# The basic 16 colors
# black
color0 #073642
color8 #93a1a1

# red
color1 #dc322f
color9 #cb4b16

# green
color2  #859900
color10 #586e75

# yellow
color3  #b58900
color11 #657b83

# blue
color4  #268bd2
color12 #839496

# magenta
color5  #d33682
color13 #6c71c4

# cyan
color6  #2aa198
color14 #93a1a1

# white
color7  #eee8d5
color15 #fdf6e3