font_family	 Iosevka
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 16.0

# tab separator style
tab_bar_style separator

# custom keybindings map ctrl++enter new_window
map ctrl+q close_tab
map ctrl+tab next_tab

# splits 
map F5 launch --location=hsplit
map F6 launch --location=vsplit
map F7 layout_action rotate
map shift+up move_window up
map shift+left move_window left
map shift+right move_window right
map shift+down move_window down

map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# force swayland; window decorations currently don't work on wayland itself 
linux_display_server x11

# vim:ft=kitty

## name: GitHub Dark
## author: GitHub
## license: MIT

#: The basic colors

foreground #c9d1d9
background #0d1117
selection_foreground #0d1117
selection_background #58a6ff


#: Cursor colors

cursor #58a6ff


#: Tab bar colors

tab_bar_background #010409
active_tab_foreground #c9d1d9
active_tab_background #0d1117
inactive_tab_foreground #8b949e
inactive_tab_background #010409


#: The basic 16 colors

#: black
color0 #484f58
color8 #6e7681

#: red
color1 #ff7b72
color9 #ffa198

#: green
color2 #3fb950
color10 #56d364

#: yellow
color3 #d29922
color11 #e3b341

#: blue
color4 #58a6ff
color12 #79c0ff

#: magenta
color5 #bc8cff
color13 #d2a8ff

#: cyan
color6 #39c5cf
color14 #56d4dd

#: white
color7 #b1bac4
color15 #ffffff
